//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
namespace World
{
	public class Edge
	{
		public int index;
		public Center d0; 	// Delaunay edge
		public Center d1; 	// Delaunay edge
		public Corner v0; 	// Voronoi edge
		public Corner v1; 	// Voronoi edge
		public Vector2f midpoint; 	// halfway between v0, v1
		public int river;  			// volume of water, or 0
		public Edge ()
		{
		}
	}
}

